# Generated by Django 5.0.4 on 2024-06-17 03:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_respuesta', models.CharField(blank=True, max_length=3, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('numero_cuotas', models.IntegerField(blank=True, null=True)),
                ('monto_cuota', models.FloatField(blank=True, null=True)),
                ('fecha_autorizacion', models.CharField(blank=True, max_length=5, null=True)),
                ('fechaHora_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('saldo_transaccion', models.FloatField(blank=True, null=True)),
                ('decision_vendedor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Enviado'), (4, 'Entregado'), (5, 'Cancelado'), (6, 'Preparando despacho'), (7, 'En transito')], default=1)),
                ('informacion_adicional', models.CharField(max_length=120)),
                ('fecha_recivo', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(blank=True, upload_to='producto/%Y/%m/%d/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, max_length=50, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
