# Generated by Django 5.0.4 on 2024-05-23 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Usuario.cliente'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Pedidos.categoria'),
        ),
    ]
