# Generated by Django 5.0.4 on 2024-07-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_recivo',
            new_name='fecha_recibo',
        ),
    ]
