# Generated by Django 5.0.4 on 2024-06-02 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('run', models.IntegerField(unique=True)),
                ('dv_run', models.CharField(max_length=1)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=45)),
                ('numero_telefonico', models.CharField(max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=70)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario. Un usuario obtendrá todos los permisos concedidos a cada uno de sus grupos.', related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='auth.permission', verbose_name='Permisos de usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuario.usuario')),
                ('contrasena_cambiada', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('Usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuario.usuario')),
            ],
            options={
                'abstract': False,
            },
            bases=('Usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuario.usuario')),
            ],
            options={
                'abstract': False,
            },
            bases=('Usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuario.usuario')),
            ],
            options={
                'abstract': False,
            },
            bases=('Usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuario.usuario')),
            ],
            options={
                'abstract': False,
            },
            bases=('Usuario.usuario',),
        ),
    ]
